unguarded cexception
Guarded statement
------g() enters ---------
------g() leaves ---------
------f() enters ---------
------h() enters ---------
Exception caught in f() from default (main) subsystem
Exception happened:
cexception generated in h(), code = -3
after the guarded block
